kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access-myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-myapp
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user0   # Change the user name here

